spring:
  profiles:
    active: env
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.15.135:3306/subway
    username: root
    password: masterpw
  flyway:
    enabled: true
    baseline-on-migrate: true